Repository modelcontextprotocol/python-sdk, pull requests merged in 2025-09, with the labels that each got.

#525 Python lint: Ruff rules for pylint and code complexity
  pyproject.toml
  src/mcp/server/fastmcp/server.py
  src/mcp/server/fastmcp/utilities/func_metadata.py
  src/mcp/server/lowlevel/server.py
  src/mcp/server/streamable_http.py
Labels: needs more work

#1380 Issue 1379 patch - Fix MCP server OAuth not working with Visual Studio Code and others with extra grant_types
  src/mcp/server/auth/handlers/register.py
  src/mcp/shared/auth.py
  tests/server/fastmcp/auth/test_auth_integration.py
Labels: needs more eyes, auth

#1381 Add comprehensive Unicode tests for streamable HTTP transport
  tests/client/test_http_unicode.py
Labels: needs more work

#775 fix: improve misleading warning for progress callback exceptions
  src/mcp/shared/session.py
  tests/shared/test_progress_notifications.py
Labels: bug, needs maintainer action

#975 fix: catch and rethrow SSEError during SSE connection establishment
  src/mcp/client/sse.py
Labels: bug
